from .enrichment import NFeMinerBaseGenerateModel, NFeMinerJSONValidator
from .elasticsearch import NFeMinerElasticSearch
from .classification import NFeMinerGTINEstimator
from .clustering import NFeCluster
from typing import Union, Optional, List, Dict

class NFeMiner:
    """
    Facade for semantic text enrichment models, using any model
    compatible with the BaseModel interface (e.g., fine-tuned, OpenAI's GPT).

    Parameters:
        model (BaseModel): An instance of a model that implements the 'generate' method.

    Methods:
        enrichment(text: str) -> str:
            Performs semantic enrichment of the provided text using the model.
    """

    def __init__(self, model: NFeMinerBaseGenerateModel, index_file_path: str, index_name="nfe_products"):
        self.model = model
        if index_file_path is not None:
            self.elasticsearch = NFeMinerElasticSearch()
            self.index_name = index_name
            self.elasticsearch.index_service.create_index(self.index_name, index_file_path)
        else:
            self.elasticsearch = None
        self.estimator = NFeMinerGTINEstimator()
        self.clusterizer = NFeCluster()

    def enrichment(self, invoice_id: str, item_id: str, ncm_code: str, gtin_code: str, sales_unit: str, quantity_sold: float, unit_price: float, description: str) -> dict:
        """
        Performs text enrichment using the encapsulated model.

        Args:
            id_nfe (str): Unique identifier of the electronic invoice (NFe).
            id_item (str): Identifier of the item within the NFe.
            ncm (str): Mercosur Common Nomenclature (NCM) code used for tax classification.
            gtin (str): Global Trade Item Number (GTIN), also known as the barcode.
            unidade_comercializacao (str): Unit of measure used for selling the item (e.g., 'kg', 'pcs').
            quantidade_comercializada (float): Total quantity of the item sold.
            valor_unitario (float): Unit price of the item.
            descricao (str): Textual description of the item.

        Returns:
            dict: Enriched text generated by the model.
        """
        from json import loads
        prompt = f"""ID NFe: {invoice_id}
ID Item: {item_id}
Nomenclatura Comum do Mercosul (NCM): {ncm_code}
Global Trade Item Number (GTIN): {gtin_code}
Unidade de Comercialização: {sales_unit}
Quantidade Comercializada: {quantity_sold}
Valor Unitário: {unit_price}
Descrição: {description}"""
        response = self.model.generate(prompt).replace('```json','').replace('```','')
        return loads(response)

    def enrichment_and_index(self, raw_data: Union[Dict, List[Dict]], batch_size: int = 500) -> Dict[str, str]:
        """
        Enriches the input data and indexes the enriched documents into Elasticsearch.

        Args:
            raw_data (Union[Dict, List[Dict]]): Raw input data to be enriched and indexed. Can be a single dictionary or a list of dictionaries.
            batch_size (int, optional): Number of documents to index per batch. Default is 500.

        Returns:
            Dict[str, str]: A dictionary with a message indicating the number of documents successfully indexed.

        Raises:
            ValueError: If the input data is not a dictionary or a list of dictionaries.
            ValueError: If the keys in raw_data do not match the expected parameters of the enrichment function.
        """
        if isinstance(raw_data, dict):
            enriched_data = [self.enrichment(**raw_data)]
        elif isinstance(raw_data, list):
            enriched_data = [self.enrichment(**item) for item in raw_data]
        else:
            raise ValueError("Input data must be a dictionary or list of dictionaries.")

        return self.elasticsearch.document_service.index_documents(self.index_name, enriched_data, batch_size=batch_size)

    def search_string(self, value:str):
        """
        Performs a full-text search across all fields in the index using the provided string.

        Args:
            value (str): The string value to search for.

        Returns:
            dict: The search results returned by Elasticsearch.
        """
        query = {
            "query": {
                "query_string": {
                    "query": value
                }
            }
        }
        return self.elasticsearch.document_service.search_documents(self.index_name, query)

    def search_all(self):
        """
        Retrieves all documents from the specified Elasticsearch index.

        Returns:
            dict: All documents indexed under the given index.
        """
        query = {
            "query": {
                "match_all": {}
            }
        }
        return self.elasticsearch.document_service.search_documents(self.index_name, query)

    def search_numeric_term(self, field: str, value: Union[int, float]):
        """
        Searches for documents where a specific field matches an exact numeric value.

        Args:
            field (str): The field name to be searched.
            value (int | float): The exact numeric value to match.

        Returns:
            dict: Documents that contain the exact value in the specified field.
        """
        query = {
            "query": {
                "term": {
                    field: value
                }
            }
        }
        return self.elasticsearch.document_service.search_documents(self.index_name, query)

    def search_numeric_range(self, field: str, gte: Optional[float] = None, lte: Optional[float] = None):
        """
        Searches for documents where a numeric field value falls within a specified range.

        Args:
            field (str): The field name to be searched.
            gte (float, optional): Minimum value (inclusive). Defaults to None.
            lte (float, optional): Maximum value (inclusive). Defaults to None.

        Returns:
            dict: Documents that have values in the specified numeric range.
        """
        range_query = {}
        if gte is not None:
            range_query["gte"] = gte
        if lte is not None:
            range_query["lte"] = lte

        query = {
            "query": {
                "range": {
                    field: range_query
                }
            }
        }
        return self.elasticsearch.document_service.search_documents(self.index_name, query)

    def search_combined(self, must: List[dict] = [], should: List[dict] = [], must_not: List[dict] = []):
        """
        Executes a combined boolean search using 'must', 'should', and 'must_not' conditions.

        Args:
            must (List[dict]): List of conditions that must be satisfied.
            should (List[dict]): List of conditions that are optional but improve relevance.
            must_not (List[dict]): List of conditions that must not be satisfied.

        Returns:
            dict: Documents that match the combined boolean query.
        """
        query = {
            "query": {
                "bool": {
                    "must": must,
                    "should": should,
                    "must_not": must_not
                }
            }
        }
        return self.elasticsearch.document_service.search_documents(self.index_name, query)

    def gtin_estimator(self, description: str) -> dict:
        return self.estimator.gtin_classifier(description)

    def gtin_estimator_batch(self, descriptions: List[str]) -> List[dict]:
        from concurrent.futures import ThreadPoolExecutor

        with ThreadPoolExecutor() as executor:
            results = list(executor.map(self.estimator.gtin_classifier, descriptions))
        return results

    def clustering(self, descriptions: List[str]) -> dict:
        self.clusterizer.pipeline(descriptions)
        return self.clusterizer.output()